import * as api from './api.js';
import {tiers,tierOf,titleOf} from './config.js';
import {zipImages,normalizeImage} from './import.js';
import {exportBoard,downloadItem} from './export.js';

const $=(s,r=document)=>r.querySelector(s);
const icon=(name)=>`<i data-lucide="${name}" aria-hidden="true"></i>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const decorate=()=>lucide.createIcons({icons:lucide.icons,attrs:{'stroke-width':1.7}});
const state={exporting:false,projects:[],projectId:null,items:[],comments:[],editor:false,tab:'board',selected:null,drag:null,ready:false};
let syncTimer,refreshRunning=false,refreshAgain=false,detailItem=null;
$('#app').innerHTML=`
<header class="site-header"><a class="brand" href="./"><span class="brand-symbol">${icon('flask-conical')}</span><span>갈드컵 연구소<small>GALDCUP LAB</small></span></a><div class="header-right"><span id="connection" class="connection">연결 중</span><button id="edit-mode" class="button primary">${icon('lock-keyhole')} 수정하기</button></div></header>
<main><section class="page-heading"><div><div class="eyebrow">THE TIER IS YOURS</div><h1>순위는 함께,<br class="mobile-break"> 의견은 자유롭게.</h1><p>정답 없는 순위에, 당신의 한 표와 한마디.</p></div><div class="overview"><div><strong id="total-items">—</strong><span>등록 항목</span></div><div><strong id="total-comments">—</strong><span>모인 의견</span></div></div></section>
<div id="demo-banner" class="demo-banner" ${api.live?'hidden':''}><span><b>체험 모드</b> 예시 보드입니다. 변경은 이 브라우저에만 저장됩니다.</span><button id="demo-help">사용 안내 ${icon('circle-help')}</button></div>
<section class="project-bar" aria-label="프로젝트 관리"><div class="project-identity"><span class="eyebrow">PROJECT</span><label class="sr-only" for="project-select">프로젝트 선택</label><select id="project-select"><option>프로젝트 불러오는 중</option></select><span id="save-status" role="status">변경 사항은 자동 저장됩니다.</span></div><div class="project-actions"><button id="projects-button" class="button subtle">${icon('folder-open')} 프로젝트 목록</button><button id="new-project" class="button subtle">${icon('plus')} 새 프로젝트</button><button id="save-project" class="button subtle" disabled>${icon('save')} 저장</button><button id="export-board" class="button primary">${icon('image-down')} PNG 저장</button></div></section>
<div class="workspace"><section class="main-panel"><div class="panel-toolbar"><div class="tabs" role="tablist" aria-label="보기 선택"><button id="board-tab" role="tab" aria-selected="true" class="active">${icon('layers')} 티어 보드</button><button id="opinions-tab" role="tab" aria-selected="false">${icon('message-square')} 의견 모아보기</button></div><span class="board-caption">모두의 티어리스트 <span class="edition">01</span></span></div>
<div class="board-tools"><span id="mode-hint">항목을 눌러 크게 보고 의견을 남겨 보세요.</span><div class="tool-actions"><button id="zip-button" class="button subtle" disabled>${icon('archive')} ZIP 가져오기</button><button id="add-button" class="button subtle" disabled>${icon('plus')} 항목 추가</button></div></div>
<div id="board" role="tabpanel" aria-labelledby="board-tab"><div class="loading">티어 보드를 불러오는 중입니다.</div></div><div id="opinions" role="tabpanel" aria-labelledby="opinions-tab" hidden></div>
<div class="board-footer"><span>${icon('grip-vertical')} 편집 모드에서 드래그하여 순위를 바꿀 수 있어요.</span><span>GOAT TO JOAT</span></div></section>
<aside class="discussion-sidebar"><div class="aside-title"><h2>연구소의 목소리</h2>${icon('message-square')}</div><p class="aside-subtitle">서로 다른 생각이 순위를 만듭니다.</p><div class="sidebar-section"><div class="section-label">지금 가장 뜨거운 항목<span>TOP 3</span></div><div id="popular"></div></div><div class="sidebar-section recent"><div class="section-label">최근 남긴 의견<span id="recent-count">0</span></div><div id="recent"></div></div><div class="discussion-tip"><span class="tip-line"></span><p>취향은 달라도 괜찮아요.<br><strong>사람보다 의견에 집중해 주세요.</strong></p></div></aside></div>
<footer><span class="footer-brand">갈드컵 연구소 <span>© 2026</span></span><span>좋은 논쟁은 좋은 근거에서.</span></footer></main>
<input type="file" id="zip-input" accept=".zip,application/zip" hidden>
<dialog id="modal" aria-labelledby="modal-title"></dialog><dialog id="lightbox" aria-label="이미지 크게 보기"></dialog>`;
const modal=$('#modal'),lightbox=$('#lightbox');
function toast(msg,error=false){const el=$('#toast');el.textContent=msg;el.className=error?'visible error':'visible';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='',4500);}
async function action(fn){try{return await fn();}catch(e){console.error(e);toast(e.message||'처리하지 못했습니다. 다시 시도해 주세요.',true);}}
function status(value){const el=$('#connection');el.className=`connection ${value}`;el.textContent={demo:'로컬 체험',live:'실시간 연결',reconnecting:'연결 복구 중',offline:'오프라인',error:'연결 확인 필요'}[value]||'연결 중';}
async function refresh(){
 if(state.drag){refreshAgain=true;return;}
 if(refreshRunning){refreshAgain=true;return;}refreshRunning=true;
 try{const [data,editor]=await Promise.all([api.snapshot(),api.isEditor()]);if(data.projectId!==api.getProjectId()){refreshAgain=true;return;}Object.assign(state,data,{editor,ready:true});render();}
 catch(e){status('error');if(!state.ready){$('#board').innerHTML=`<div class="empty"><h3>보드를 불러오지 못했어요.</h3><p>연결과 Supabase 설정을 확인한 뒤 다시 시도해 주세요.</p><button id="retry" class="button subtle">다시 시도</button></div>`;$('#retry').onclick=refresh;}console.error(e);}
 finally{refreshRunning=false;if(refreshAgain){refreshAgain=false;queueRefresh();}}
}
function queueRefresh(){clearTimeout(syncTimer);syncTimer=setTimeout(refresh,120);}
const commentsOf=id=>state.comments.filter(c=>c.item_id===id);
const visibleComments=()=>state.comments.filter(c=>state.items.some(i=>i.id===c.item_id));
const preview=item=>api.imageUrl(item)?`<img src="${esc(api.imageUrl(item))}" alt="${esc(titleOf(item))}" loading="lazy" draggable="false">`:`<span class="glyph ${item.label.length>8?'long':''}">${esc(item.label)}</span>`;
function render(){
 $('#project-select').innerHTML=state.projects.map(p=>`<option value="${p.id}" ${p.id===state.projectId?'selected':''}>${esc(p.name)}</option>`).join('');
 $('#new-project').disabled=false;$('#save-project').disabled=!state.editor||!state.projectId;$('#export-board').disabled=!state.projectId||state.exporting;
 const project=state.projects.find(p=>p.id===state.projectId);
 $('#save-status').textContent=project?`자동 저장 · 최근 변경 ${formatTime(project.updated_at)}${api.live?'':' · 이 브라우저에 보관'}`:'새 프로젝트를 만들어 주세요.';
 $('#total-items').textContent=state.items.length;$('#total-comments').textContent=visibleComments().length;
 $('#edit-mode').innerHTML=state.editor?`${icon('check')} 편집 완료`:`${icon('lock-keyhole')} 수정하기`;
 $('#edit-mode').classList.toggle('editing',state.editor);
 $('#zip-button').disabled=!state.editor||!state.projectId;$('#add-button').disabled=!state.editor||!state.projectId;
 $('#mode-hint').textContent=state.editor?'편집 중 · 드래그하거나 항목을 눌러 티어를 바꿔 보세요.':'항목을 눌러 크게 보고 의견을 남겨 보세요.';
 $('#board').innerHTML=tiers.map(t=>{const items=state.items.filter(i=>i.tier===t.id).sort((a,b)=>a.position-b.position||a.id.localeCompare(b.id));return `<section class="tier-row ${t.id==='unranked'?'unranked':''}" data-tier="${t.id}" aria-label="${t.label} 티어"><div class="tier-label" style="--tier:${t.color}"><strong>${t.label}</strong><span>${items.length}</span></div><div class="tier-items">${items.map(item=>`<button class="item-card ${api.imageUrl(item)?'has-image':'text-card'}" data-item="${item.id}" draggable="${state.editor}" aria-label="${esc(titleOf(item))}, ${t.label} 티어, 의견 ${commentsOf(item.id).length}개">${preview(item)}${api.imageUrl(item)&&item.label?`<span class="card-label">${esc(item.label)}</span>`:''}${commentsOf(item.id).length?`<span class="comment-badge">${commentsOf(item.id).length}</span>`:''}</button>`).join('')}${!items.length?`<span class="tier-empty">${state.editor?'이곳에 항목을 놓으세요':t.id==='unranked'?'새로운 항목을 기다리고 있어요':'아직 등록된 항목이 없어요'}</span>`:''}</div></section>`;}).join('');
 renderOpinions();renderSidebar();
 if(modal.open&&state.selected){const current=state.items.find(i=>i.id===state.selected);if(!current){modal.close();state.selected=null;toast('이 항목이 삭제되었습니다.');}else{$('#detail-comments')&&( $('#detail-comments').innerHTML=commentList(current.id));$('#detail-distribution')&&($('#detail-distribution').innerHTML=distribution(current.id));if($('#detail-tier')){$('#detail-tier').textContent=tierOf(current.tier).label;$('#detail-tier').style.setProperty('--tier',tierOf(current.tier).color);$('#modal-title').textContent=titleOf(current);}if(detailItem&&(detailItem.label!==current.label||detailItem.image_path!==current.image_path)){const img=api.imageUrl(current);$('#detail-image').innerHTML=preview(current)+(img?`<span>${icon('maximize-2')} 이미지 크게 보기</span>`:'');$('#detail-image').disabled=!img;$('#detail-image').classList.toggle('only-text',!img);$('#detail-image').onclick=img?()=>openLightbox(current):null;}}}
 decorate();
}
function distribution(id){const list=commentsOf(id).filter(c=>c.suggested_tier);if(!list.length)return '<p class="muted small">제안된 티어가 아직 없어요.</p>';const counts=tiers.filter(t=>t.id!=='unranked').map(t=>({...t,n:list.filter(c=>c.suggested_tier===t.id).length})).filter(t=>t.n);return `<div class="distribution" aria-label="제안 티어 분포">${counts.map(t=>`<span style="background:${t.color};flex:${t.n}" title="${t.label}: ${t.n}개">${t.label} ${t.n}</span>`).join('')}</div><p class="muted micro">티어를 제안한 의견 ${list.length}개 기준 · 1인 1표 집계가 아닙니다.</p>`;}
function renderOpinions(){const items=[...state.items].sort((a,b)=>commentsOf(b.id).length-commentsOf(a.id).length);$('#opinions').innerHTML=`<div class="opinions-intro"><h2>어떤 티어가 어울릴까요?</h2><p>의견 많은 순으로 살펴보세요. 제안한 티어는 보드에 자동 반영되지 않습니다.</p></div><div class="opinion-grid">${items.map(i=>`<button class="opinion-card" data-item="${i.id}"><span class="opinion-top"><span class="mini-image">${preview(i)}</span><span class="opinion-name">${esc(titleOf(i))}<small>현재 ${tierOf(i.tier).label} 티어</small></span><span class="count-chip">${icon('message-square')} ${commentsOf(i.id).length}</span></span>${distribution(i.id)}</button>`).join('')||'<div class="empty">항목을 추가하면 의견을 모을 수 있어요.</div>'}</div>`;}
function renderSidebar(){const comments=visibleComments();const popular=[...state.items].filter(i=>commentsOf(i.id).length).sort((a,b)=>commentsOf(b.id).length-commentsOf(a.id).length).slice(0,3);$('#popular').innerHTML=popular.length?popular.map((i,p)=>`<button class="popular-item" data-item="${i.id}"><span class="rank-number">0${p+1}</span><span class="mini-image">${preview(i)}</span><span class="popular-name">${esc(titleOf(i))}<small>${tierOf(i.tier).label} 티어</small></span><span class="muted">${commentsOf(i.id).length}</span></button>`).join(''):`<div class="quiet-empty">${icon('chart-no-axes-column-increasing')}<p>아직은 조용한 연구소.<br>첫 의견으로 이야기를 열어 주세요.</p></div>`;$('#recent-count').textContent=comments.length;$('#recent').innerHTML=comments.sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,4).map(c=>{const item=state.items.find(i=>i.id===c.item_id);return `<button class="recent-comment" data-item="${c.item_id}"><span class="recent-meta"><b>${esc(c.name)}</b><span>${esc(titleOf(item))}</span></span><p>${esc(c.body)}</p><small>${formatTime(c.created_at)}${c.suggested_tier?` · ${esc(c.suggested_tier)} 티어 제안`:''}</small></button>`;}).join('')||'<p class="muted empty-recent">항목을 선택해 이름과 의견을 남겨 보세요.</p>';}
const formatTime=date=>new Intl.DateTimeFormat('ko',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(date));
function openModal(html){state.selected=null;modal.innerHTML=html;decorate();modal.showModal();}
const closeButton=()=>`<button type="button" class="icon-button close-modal" aria-label="닫기">${icon('x')}</button>`;
function openLogin(afterLogin=null){openModal(`<form id="login-form" class="modal-content compact"><div class="modal-symbol">${icon('lock-keyhole')}</div>${closeButton()}<div class="eyebrow">EDITOR ACCESS</div><h2 id="modal-title">함께 순위를 정해 볼까요?</h2><p class="muted">편집 비밀번호를 입력하면<br>항목을 추가하고 티어를 바꿀 수 있어요.</p><label>편집 비밀번호<input name="password" type="password" autocomplete="current-password" placeholder="비밀번호 입력" required autofocus></label>${!api.live?'<p class="demo-password">체험용 비밀번호 <code>demo</code></p>':''}<p id="login-error" class="form-error" role="alert"></p><button class="button primary full" type="submit">편집 시작하기</button></form>`);$('#login-form').onsubmit=async e=>{e.preventDefault();const b=$('button[type=submit]',e.target);b.disabled=true;try{await api.login(new FormData(e.target).get('password'));modal.close();await refresh();toast('편집 모드가 켜졌습니다.');if(afterLogin)afterLogin();}catch(error){$('#login-error').textContent=error.message;}finally{b.disabled=false;}};}
$('#edit-mode').onclick=()=>state.editor?action(async()=>{await api.logout();await refresh();toast('편집을 마쳤습니다.');}):openLogin();
$('#demo-help').onclick=()=>openModal(`<div class="modal-content compact">${closeButton()}<h2 id="modal-title">먼저 자유롭게 체험해 보세요.</h2><p>수정하기에서 <code>demo</code>를 입력하면 편집할 수 있어요.</p><p>ZIP 업로드, 텍스트 추가, 티어 이동과 의견 작성이 가능합니다. 지금 데이터는 이 브라우저에만 저장되며 다른 사람에게 전달되지 않습니다.</p><p class="muted">실제 공동 편집은 함께 제공한 배포 안내에 따라 Supabase를 연결하면 활성화됩니다.</p></div>`);
function selectTab(tab){state.tab=tab;$('#board').hidden=tab!=='board';$('#opinions').hidden=tab!=='opinions';for(const name of ['board','opinions']){$(`#${name}-tab`).classList.toggle('active',tab===name);$(`#${name}-tab`).setAttribute('aria-selected',String(tab===name));}}
$('#board-tab').onclick=()=>selectTab('board');$('#opinions-tab').onclick=()=>selectTab('opinions');
$('.tabs').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();selectTab(state.tab==='board'?'opinions':'board');$(`#${state.tab}-tab`).focus();}};
for(const d of [modal,lightbox]){d.addEventListener('click',e=>{if(e.target===d&&!d.dataset.busy){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});}
modal.addEventListener('close',()=>{if(!modal.open){state.selected=null;detailItem=null;}});
document.addEventListener('click',e=>{if(e.target.closest('.close-modal'))modal.close();const card=e.target.closest('[data-item]');if(card&&!state.drag)openDetail(card.dataset.item);});
$('#board').addEventListener('dragstart',e=>{const card=e.target.closest('[data-item]');if(!state.editor||!card){e.preventDefault();return;}state.drag=card.dataset.item;e.dataTransfer.setData('text/plain',state.drag);e.dataTransfer.effectAllowed='move';card.classList.add('dragging');});
$('#board').addEventListener('dragover',e=>{if(!state.drag)return;const row=e.target.closest('[data-tier]');if(row){e.preventDefault();document.querySelectorAll('.drop-target').forEach(x=>x.classList.remove('drop-target'));row.classList.add('drop-target');}});
$('#board').addEventListener('drop',e=>{e.preventDefault();const row=e.target.closest('[data-tier]'),before=e.target.closest('[data-item]');const id=state.drag;state.drag=null;document.querySelectorAll('.drop-target').forEach(x=>x.classList.remove('drop-target'));if(row&&id&&before?.dataset.item!==id)action(async()=>{await api.moveItem(id,row.dataset.tier,before?.dataset.item||null);await refresh();toast('티어를 변경했습니다.');});});
$('#board').addEventListener('dragend',()=>{state.drag=null;document.querySelectorAll('.drop-target,.dragging').forEach(x=>x.classList.remove('drop-target','dragging'));if(refreshAgain)queueRefresh();});
function commentList(id){return commentsOf(id).sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(c=>`<article class="comment"><div class="comment-head"><b>${esc(c.name)}</b><time>${formatTime(c.created_at)}</time>${state.editor?`<button type="button" class="icon-button delete-comment" data-id="${c.id}" aria-label="의견 삭제">${icon('trash-2')}</button>`:''}</div>${c.suggested_tier?`<span class="suggested">${esc(c.suggested_tier)} 티어 제안</span>`:''}<p>${esc(c.body)}</p></article>`).join('')||'<div class="empty-comment">아직 의견이 없어요. 첫 번째 생각을 남겨 주세요.</div>';}
function openDetail(id){const item=state.items.find(i=>i.id===id);if(!item)return;const img=api.imageUrl(item);openModal(`<div class="modal-content detail-content">${closeButton()}<div class="detail-layout"><section class="detail-visual"><button id="detail-image" class="detail-image ${img?'':'only-text'}" ${img?'':'disabled'}>${preview(item)}${img?`<span>${icon('maximize-2')} 이미지 크게 보기</span>`:''}</button><div class="detail-title"><span id="detail-tier" class="tier-pill" style="--tier:${tierOf(item.tier).color}">${tierOf(item.tier).label}</span><h2 id="modal-title">${esc(titleOf(item))}</h2></div>${state.editor?`<div class="editor-controls"><label>티어 변경<select id="move-select">${tiers.map(t=>`<option value="${t.id}" ${item.tier===t.id?'selected':''}>${t.label}</option>`).join('')}</select></label><div><button id="edit-item" class="button subtle">${icon('pencil')} 내용 수정</button><button id="delete-item" class="icon-button danger" aria-label="항목 삭제">${icon('trash-2')}</button></div></div>`:''}<div class="detail-summary"><h3>제안된 티어</h3><div id="detail-distribution">${distribution(id)}</div></div></section><section class="detail-discussion"><h3>이 항목에 대한 생각</h3><form id="comment-form"><div class="form-row"><label>이름<input name="name" maxlength="30" placeholder="닉네임" value="${esc(localStorage.getItem('galdcup-name')||'')}" required></label><label>내가 생각하는 티어<select name="tier"><option value="">선택 안 함</option>${tiers.filter(t=>t.id!=='unranked').map(t=>`<option>${t.label}</option>`).join('')}</select></label></div><label class="sr-only" for="comment-body">의견</label><textarea id="comment-body" name="body" maxlength="1500" rows="3" required placeholder="왜 그렇게 생각하나요? 근거와 함께 남겨 주세요."></textarea><button class="button primary" type="submit">${icon('send')} 의견 남기기</button></form><div id="detail-comments">${commentList(id)}</div></section></div></div>`);state.selected=id;detailItem={...item};
 if(img){$('#detail-image').onclick=()=>openLightbox(item);const button=document.createElement('button');button.className='button subtle full';button.innerHTML=icon('download')+' 이 이미지 저장';button.onclick=()=>action(()=>downloadItem(item));$('.detail-visual').append(button);decorate();}
 if(state.editor){$('#move-select').onchange=e=>{e.target.disabled=true;action(async()=>{await api.moveItem(id,e.target.value);await refresh();openDetailAgain(id);toast('티어를 변경했습니다.');}).finally(()=>{e.target.disabled=false;});};$('#edit-item').onclick=()=>{modal.close();openItemForm(detailItem);};$('#delete-item').onclick=()=>{modal.close();confirmDialog('이 항목을 삭제할까요?','항목과 연결된 의견이 함께 삭제됩니다.',async()=>{await api.deleteItem(item);await refresh();toast('항목을 삭제했습니다.');});};}
 $('#comment-form').onsubmit=async e=>{e.preventDefault();const form=e.target,fd=new FormData(form),name=fd.get('name').trim(),body=fd.get('body').trim();if(!name||!body){toast('이름과 의견을 입력해 주세요.',true);return;}const submit=$('button[type=submit]',form);submit.disabled=true;await action(async()=>{await api.addComment(id,name,body,fd.get('tier'));localStorage.setItem('galdcup-name',name);$('textarea',form).value='';await refresh();toast('의견을 남겼습니다.');});submit.disabled=false;};
 $('#detail-comments').onclick=e=>{const button=e.target.closest('.delete-comment');if(button)action(async()=>{await api.deleteComment(button.dataset.id);await refresh();toast('의견을 삭제했습니다.');});};
}
function openDetailAgain(id){modal.close();openDetail(id);}
function confirmDialog(title,body,fn){openModal(`<div class="modal-content compact">${closeButton()}<h2 id="modal-title">${title}</h2><p class="muted">${body}</p><div class="form-actions"><button class="button subtle close-modal">취소</button><button id="confirm" class="button destructive">삭제하기</button></div></div>`);$('#confirm').onclick=async e=>{e.target.disabled=true;await action(async()=>{await fn();modal.close();});e.target.disabled=false;};}
function openLightbox(item){let zoom=1;lightbox.innerHTML=`<div class="lightbox-toolbar"><strong>${esc(titleOf(item))}</strong><div><button id="zoom-out" class="icon-button" aria-label="축소">${icon('minus')}</button><button id="zoom-reset" class="zoom-label">100%</button><button id="zoom-in" class="icon-button" aria-label="확대">${icon('plus')}</button><button id="close-lightbox" class="icon-button" aria-label="이미지 닫기">${icon('x')}</button></div></div><div class="image-viewport"><div class="image-stage"><img src="${esc(api.imageUrl(item))}" alt="${esc(titleOf(item))}" draggable="false"></div></div><div class="lightbox-help">마우스 휠로 확대·축소 · 드래그로 이동 · Esc로 닫기</div>`;decorate();lightbox.showModal();const viewport=$('.image-viewport',lightbox),stage=$('.image-stage',lightbox),img=$('img',stage);let baseW,baseH;
 function fit(){if(!img.naturalWidth)return;const scale=Math.min((viewport.clientWidth-48)/img.naturalWidth,(viewport.clientHeight-48)/img.naturalHeight);baseW=img.naturalWidth*scale;baseH=img.naturalHeight*scale;setZoom(1);}
 function setZoom(n){zoom=Math.max(.25,Math.min(5,n));img.style.width=`${baseW*zoom}px`;img.style.height=`${baseH*zoom}px`;stage.style.width=`${Math.max(viewport.clientWidth,baseW*zoom+48)}px`;stage.style.height=`${Math.max(viewport.clientHeight,baseH*zoom+48)}px`;$('#zoom-reset').textContent=`${Math.round(zoom*100)}%`;}
 img.onload=fit;if(img.complete)fit();$('#zoom-in').onclick=()=>setZoom(zoom*1.2);$('#zoom-out').onclick=()=>setZoom(zoom/1.2);$('#zoom-reset').onclick=fit;$('#close-lightbox').onclick=()=>lightbox.close();viewport.addEventListener('wheel',e=>{e.preventDefault();const oldW=stage.offsetWidth,oldH=stage.offsetHeight,x=viewport.scrollLeft+viewport.clientWidth/2,y=viewport.scrollTop+viewport.clientHeight/2;setZoom(zoom*Math.exp(-e.deltaY*.0015));viewport.scrollLeft=x*(stage.offsetWidth/oldW)-viewport.clientWidth/2;viewport.scrollTop=y*(stage.offsetHeight/oldH)-viewport.clientHeight/2;},{passive:false});let drag;viewport.onpointerdown=e=>{if(e.pointerType==='touch')return;drag={x:e.clientX,y:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop};viewport.setPointerCapture(e.pointerId);};viewport.onpointermove=e=>{if(drag){viewport.scrollLeft=drag.left+drag.x-e.clientX;viewport.scrollTop=drag.top+drag.y-e.clientY;}};viewport.onpointerup=viewport.onpointercancel=()=>drag=null;
}
function openItemForm(item=null){const projectAtOpen=state.projectId;openModal(`<form id="item-form" class="modal-content compact">${closeButton()}<div class="eyebrow">${item?'EDIT ITEM':'NEW ITEM'}</div><h2 id="modal-title">${item?'항목 수정':'새 항목 추가'}</h2><p class="muted">이미지, 텍스트 중 하나만 있어도 괜찮아요.</p><label>텍스트<input name="label" maxlength="120" value="${esc(item?.label||'')}" placeholder="항목 이름 또는 텍스트"></label><label class="upload-field">${icon('image-plus')} ${item?.image_path?'이미지 바꾸기':'이미지 선택'}<input name="image" type="file" accept=".png,.jpg,.jpeg,.webp,.gif"></label>${item?.image_path?'<label class="checkbox-label"><input type="checkbox" name="removeImage"> 기존 이미지 지우기</label>':''}${!item?`<label>추가할 티어<select name="tier">${tiers.map(t=>`<option value="${t.id}" ${t.id==='unranked'?'selected':''}>${t.label}</option>`).join('')}</select></label>`:''}<p class="muted micro">PNG · JPG · WebP · GIF / 최대 10MB<br>긴 변 2,048px로 저장됩니다. GIF는 정지 이미지로 변환됩니다.</p><p class="form-error" id="item-error" role="alert"></p><button class="button primary full" type="submit">${item?'변경 저장':'항목 추가'}</button></form>`);$('#item-form').onsubmit=async e=>{e.preventDefault();const form=e.target,fd=new FormData(form),label=fd.get('label').trim(),file=fd.get('image'),button=$('button[type=submit]',form);let imagePath=fd.get('removeImage')?null:item?.image_path||null,newPath=null;button.disabled=true;try{if(file?.size){button.textContent='이미지 처리 중…';newPath=await api.upload(await normalizeImage(file));imagePath=newPath;}if(!label&&!imagePath)throw Error('텍스트 또는 이미지를 넣어 주세요.');if(item)await api.editItem(item,{label,image_path:imagePath});else await api.addItems([{label,image_path:imagePath,tier:fd.get('tier')}],projectAtOpen);modal.close();await refresh();toast(item?'변경을 저장했습니다.':'새 항목을 추가했습니다.');}catch(error){if(newPath)await api.removeUploads([newPath]).catch(()=>{});$('#item-error').textContent=error.message;}finally{button.disabled=false;button.textContent=item?'변경 저장':'항목 추가';}};}
$('#add-button').onclick=()=>openItemForm();$('#zip-button').onclick=()=>$('#zip-input').click();
$('#zip-input').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;const importProject=state.projectId;openModal(`<div class="modal-content compact"><h2 id="modal-title">ZIP에서 이미지 가져오기</h2><p class="muted" id="import-status">이미지 파일을 확인하고 있어요…</p><progress id="import-progress" max="100" value="0"></progress><p class="micro muted">가져온 이미지는 대기 칸에 추가됩니다.<br>파일명이 기본 텍스트가 됩니다.</p></div>`);const prevent=e=>e.preventDefault();modal.dataset.busy='true';modal.addEventListener('cancel',prevent);let paths=[];let committed=false;try{const files=await zipImages(file);const rows=[];for(let i=0;i<files.length;i++){$('#import-status').textContent=`${i+1} / ${files.length} · ${files[i].name}`;const image_path=await api.upload(await normalizeImage(files[i]));paths.push(image_path);rows.push({label:files[i].name.replace(/\.[^.]+$/,'').slice(0,120),image_path,tier:'unranked'});$('#import-progress').value=(i+1)/files.length*100;}await api.addItems(rows,importProject);committed=true;modal.close();await refresh();toast(`이미지 ${files.length}개를 대기 칸에 추가했습니다.`);}catch(error){if(!committed)await api.removeUploads(paths).catch(()=>{});modal.close();toast(error.message||'가져오지 못했습니다.',true);}finally{delete modal.dataset.busy;modal.removeEventListener('cancel',prevent);}};
async function switchProject(id){
 if(!state.projects.some(p=>p.id===id))return;
 api.selectProject(id);state.projectId=id;state.items=[];state.comments=[];modal.close();lightbox.close();
 history.replaceState(null,'',`#project=${encodeURIComponent(id)}`);render();await refresh();
}
$('#project-select').onchange=e=>action(()=>switchProject(e.target.value));
function openProjects(){openModal(`<div class="modal-content project-library">${closeButton()}<div class="eyebrow">ALL PROJECTS</div><h2 id="modal-title">저장된 프로젝트</h2><p class="muted">각 프로젝트의 이미지, 티어와 의견이 따로 보관됩니다.</p><div class="project-grid">${state.projects.map(p=>`<button class="project-card" data-project="${p.id}"><span class="project-card-symbol">${icon('layers')}</span><strong>${esc(p.name)}</strong><small>최근 변경 ${formatTime(p.updated_at)}</small><span>${p.id===state.projectId?'현재 열려 있음':'프로젝트 열기'}</span></button>`).join('')}</div><button id="library-new" class="button primary">${icon('plus')} 새 프로젝트 만들기</button></div>`);$('#library-new').onclick=()=>{modal.close();requestNewProject();};modal.querySelectorAll('[data-project]').forEach(button=>button.onclick=()=>action(()=>switchProject(button.dataset.project)));}
function requestNewProject(){if(!state.editor){openLogin(openNewProject);return;}openNewProject();}
function openNewProject(){openModal(`<form id="project-form" class="modal-content compact">${closeButton()}<div class="eyebrow">NEW PROJECT</div><h2 id="modal-title">새 티어리스트 만들기</h2><p class="muted">기존 프로젝트는 그대로 보관하고, 빈 티어리스트로 시작합니다.</p><label>프로젝트 이름<input name="name" maxlength="80" required placeholder="예: 2026 게임 캐릭터 순위" autofocus></label><p id="project-error" class="form-error" role="alert"></p><button type="submit" class="button primary full">프로젝트 만들기</button></form>`);$('#project-form').onsubmit=async e=>{e.preventDefault();const button=$('button[type=submit]',e.target);button.disabled=true;try{const id=await api.createProject(new FormData(e.target).get('name'));api.selectProject(id);modal.close();history.replaceState(null,'',`#project=${id}`);await refresh();toast('새 프로젝트를 만들었습니다. ZIP이나 항목을 추가해 보세요.');}catch(error){$('#project-error').textContent=error.message;}finally{button.disabled=false;}};}
$('#projects-button').onclick=openProjects;$('#new-project').onclick=requestNewProject;
$('#save-project').onclick=async e=>{const button=e.currentTarget;button.disabled=true;$('#save-status').textContent='저장 확인 중…';try{await api.saveProject();await refresh();toast(api.live?'프로젝트를 서버에 저장했습니다.':'프로젝트를 이 브라우저에 저장했습니다.');}catch(error){$('#save-status').textContent='저장 실패 · 다시 시도해 주세요.';toast(error.message,true);}finally{button.disabled=!state.editor;}};
$('#export-board').onclick=async e=>{const button=e.currentTarget,project=structuredClone(state.projects.find(p=>p.id===state.projectId)),items=structuredClone(state.items);state.exporting=true;button.disabled=true;try{await exportBoard(project,items,(done,total)=>button.textContent=`이미지 준비 ${done}/${total}`);toast('티어리스트 이미지를 저장했습니다.');}catch(error){toast(error.message,true);}finally{state.exporting=false;button.disabled=false;button.innerHTML=icon('image-down')+' PNG 저장';decorate();}};
const initialProject=new URLSearchParams(location.hash.slice(1)).get('project');if(initialProject)api.selectProject(initialProject);
window.addEventListener('hashchange',()=>{const id=new URLSearchParams(location.hash.slice(1)).get('project');if(id&&!modal.dataset.busy)action(()=>switchProject(id));});
api.subscribe(queueRefresh,status);refresh();decorate();
